export const GET_TODOLIST = 'GET_TODOLIST';
export const RECIEVED_TODOS = 'RECIEVED_TODOS';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const RESET_TODOLIST= 'RESET_TODOLIST';

export const EDIT_TODO = 'EDIT_TODO';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const SET_SELECTED_TODO = "SET_SELECTED_TODO";
export const EDIT_SELECTED_TODO = "EDIT_SELECTED_TODO";
export const SAVE_SELECTED_TODO = "SAVE_SELECTED_TODO";
export const SAVE_SELECTED_TODO_SUCCESS = "SAVE_SELECTED_TODO_SUCCESS";
export const RESET_SELECTED_TODO = "RESET_SELECTED_TODO";

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_INCOMPLETED: "SHOW_INCOMPLETED"
}

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const TOGGLE_COMPLETE_SUCCESS = "TOGGLE_COMPLETE_SUCCESS";

export const START_REQUEST = "START_REQUEST";
export const FINISH_REQUEST = "FINISH_REQUEST";

export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const AUTH_FAILD = "AUTH_FAILD";